Update 05.proteolysis.md
jessegmeyerlab/proteomics-tutorial pull request #25
Opened 2022-02-06 12:24 UTC by norbertvolkmar

Please provide a description of your changes:

- added small section on proteinase K
- corrected minor grammatical mistakes
- I think we should define the species which the statement in line 14 relates to

Please check the following about your suggested changed:
- [x ] The new text has one sentence per line
- [x] preprints that are cited are listed as an issue for discussion and peer review

2022-02-06 13:03 UTC, jessegmeyerlab requested changes
Thanks so much for checking this section!!!

2022-02-06 13:03 UTC, jessegmeyerlab commented on content/05.proteolysis.md
> +Pepsin works at an optimum pH from 1-4 and, in a pH-depended manner, it specifically cleaves Trp, Phe, Tyr and  Leu [@PMID:25823410].
```suggestion
Pepsin works at an optimum pH from 1-4 and specifically cleaves Trp, Phe, Tyr and  Leu [@PMID:25823410]. 
```

2022-02-06 13:03 UTC, jessegmeyerlab commented on content/05.proteolysis.md
> +The epithet 'K'is derived from its ability to efficiently hydrolyse keratin [@PMID:4373242].
```suggestion
The epithet 'K' is derived from its ability to efficiently hydrolyse keratin [@PMID:4373242].
```

2022-02-06 13:03 UTC, jessegmeyerlab commented on content/05.proteolysis.md
> +It is a member of the subtilisin family of proteases and is relatively unspecific with a preference for cleaving at hydrophobic and aromatic amino acid residues and show optimal activity at pH 7.5 -
```suggestion
It is a member of the subtilisin family of proteases and is relatively unspecific with a preference for proteolysis at hydrophobic and aromatic amino acid residues [@DOI:https://doi.org/10.1016/B978-0-12-382219-2.00714-6]. 
The optimal enzyme activity is between pH 7.5 and 12.
```

2022-02-06 13:03 UTC, jessegmeyerlab commented on content/05.proteolysis.md
> +Peptides that are too long are difficult to identify by tandem mass spectrometry, or may be lost during sample preparation due to peptides that are too short are less likely to uniquely match to a si
```suggestion
Peptides that are too long are difficult to identify by tandem mass spectrometry, or may be lost during sample preparation due to irreversible binding with solid-phase extraction sorbents.
Peptides that are too short are also not useful because they may match to many proteins during protein inference. 
```

2022-02-06 13:03 UTC, jessegmeyerlab commented on content/05.proteolysis.md
> +rypsin is less efficient in cleaving Lysthan aginine, which could limit the quality of quantitation from tryptic peptides.
```suggestion
Trypsin is less efficient at cleaving Lys than Arg, which could limit the quality of quantitation from tryptic peptides.
```

2022-02-06 13:03 UTC, jessegmeyerlab commented on content/05.proteolysis.md
> +Hence, to achieve complete protein digestion with minimal missed cleavages, Lys-C is often used in parallel to complement tryspin digestion [@PMID:23017020].
```suggestion
Hence, to achieve complete protein digestion with minimal missed cleavages, Lys-C is often used in simultaneously with trypsin digestion [@PMID:23017020].
```

2022-02-06 13:03 UTC, jessegmeyerlab commented on content/05.proteolysis.md
> +The optimum activity of this enzyme is between pH 4 - 9.
```suggestion
The optimum activity of this enzyme is between pH 4 and 9.  
```

2022-02-06 13:03 UTC, jessegmeyerlab commented on content/05.proteolysis.md
> +The optimum activity of this enzyme is between pH 4 - 9.
the automated manuscript building gets confused when sentences end in what looks like math (4-9) so I changed this to 4 and 9

2022-02-06 13:03 UTC, jessegmeyerlab commented on content/05.proteolysis.md
> +Asp-N catalyzes the hydrolysis of peptide bonds N-terminal of aspartate residues.
```suggestion
Asp-N catalyzes the hydrolysis of peptide bonds at the N-terminal of aspartate residues. 
```

2022-02-06 13:03 UTC, jessegmeyerlab commented on content/05.proteolysis.md
> +Chymotrypsin or chymotrypsinogen A is a serine protease obtained from porcine or bovine pancreas with an optimum pH range from 7.8 - 8.0 [@PMID:3555886].
```suggestion
Chymotrypsin or chymotrypsinogen A is a serine protease obtained from porcine or bovine pancreas with an optimum pH range from 7.8 to 8.0 [@PMID:3555886]. 
```

2022-02-06 13:03 UTC, jessegmeyerlab commented on content/05.proteolysis.md
> +Pepsin A, commonly known as pepsin, is an aspartic protease obtained from bovine or porcine pancreas, and was identified and crystallized and was awarded the Nobel prize [ [@PMID:12089768];@PMID:1987
```suggestion
Pepsin A, commonly known as pepsin, is an aspartic protease obtained from bovine or porcine pancreas [@PMID:12089768].
Pepsin was one of several proteins crystalized by John Northrop, who shared the 1946 Nobel prize in chemistry for this work [@PMID:19872561;@PMID:19872562; @PMID:17758437;@URL:https://www.nobelprize.org/prizes/chemistry/1946/speedread/].
```

2022-02-06 13:03 UTC, jessegmeyerlab commented on content/05.proteolysis.md
> +Pepsin A, commonly known as pepsin, is an aspartic protease obtained from bovine or porcine pancreas, and was identified and crystallized and was awarded the Nobel prize [ [@PMID:12089768];@PMID:1987
wanted to emphasize the nobel prize a little

2022-02-06 13:03 UTC, jessegmeyerlab commented on content/05.proteolysis.md
> +It is a member of the subtilisin family of proteases and is relatively unspecific with a preference for cleaving at hydrophobic and aromatic amino acid residues and show optimal activity at pH 7.5 -
sentence gets a little long

2022-02-07 06:51 UTC, norbertvolkmar commented
happy with the changes - hopefully i did the right thing by pressing 'commit changes'. (still just a bit confused about how to navigate the file review process in Github)

2022-02-07 13:56 UTC, jessegmeyerlab approved these changes

2022-02-07 13:56 UTC, merged

2022-02-07 13:58 UTC, jessegmeyerlab commented
Yes if you agree with a suggestion clicking 'commit' will add them. Otherwise you can comment and we can discuss, or you can edit your branch related to this pull request and make any custom change. 

Merged these changes ! thanks for contributing!!