Update 12 raw data analysis
jessegmeyerlab/proteomics-tutorial pull request #46
Opened 2022-08-09 08:33 UTC by dschust-r

Added QC section with software table

Please provide a description of your changes:

Please check the following about your suggested changed:
- [x] The new text has one sentence per line
- [ ] preprints that are cited are listed as an issue for discussion and peer review

The only preprint cited is the AlphaPept preprint (10.1101/2021.07.23.453379), how exactly would you like to discuss this one? Should I post an issue on it or mention in the table that it is a preprint?

2022-08-09 13:23 UTC, jessegmeyerlab commented
Thanks for contributing more! I should be able to review this over the weekend. 

For preprints we just want to make sure we vet their claims since they aren't peer reviewed. There is a template for new paper discussion if you click the new issue button. Since it's software you don't have to be to harsh in the review - either it does what they say or it doesn't. 

Thanks again for contributing!!

2022-08-11 13:59 UTC, dschust-r commented
Edit: Posted an issue about the AlphaPept preprint

2022-08-13 21:28 UTC, jessegmeyerlab requested changes
this is great overall, thank you Dina! most suggestions are to break into paragraphs. Let me know what you think

2022-08-13 21:28 UTC, jessegmeyerlab commented on content/12.raw-data-analysis.md
> +During the calibration you can check injection times and intensity of the ions of your calibration mix.
```suggestion
During the calibration you can check injection times (for ion trap instruments) and intensity of the ions in the calibration mix.
```

2022-08-13 21:28 UTC, jessegmeyerlab commented on content/12.raw-data-analysis.md
> +Instrument calibrations in regular intervals help ensure that performance is appropriate.
```suggestion
Instrument calibrations in regular intervals help ensure that performance is maintained.
Often basic calibration and sensitivity can be checked by direct infusion of a standard.
```

2022-08-13 21:28 UTC, jessegmeyerlab commented on content/12.raw-data-analysis.md
> +To find out if your mass spectrometer is performing as expected, you can analyze complex samples, such as tryptic digests of whole-cell lysates (e.g. HeLa cells, HEK cells, yeast, etc.) or tryptic di
```suggestion

After ensuring good calibration and signal with the simple calibration mixture, it is advisable to analyze complex samples, such as tryptic digests of whole-cell lysates (e.g. HeLa cells, HEK cells, yeast, etc.) or tryptic digests of purified proteins.
The additional check with a complex sample ensures all aspects of the system are working together correctly, especially the liquid chromatography and emitter.
```

2022-08-13 21:28 UTC, jessegmeyerlab commented on content/12.raw-data-analysis.md
> +These digests should be analyzed after every instrument calibration and if required in between samples when acquiring more extensive batches.
```suggestion
These digests should be analyzed after every instrument calibration and periodically between samples when acquiring more extensive batches.
```

2022-08-13 21:28 UTC, jessegmeyerlab commented on content/12.raw-data-analysis.md
> +Measured tryptic digests can be searched with software of your choice and the numbers of identified peptide precursors and proteins can be compared.
```suggestion
Data measured from tryptic digests should be analyzed by the software of your choice and the numbers of identified peptide precursors and proteins can be compared with previous controls for consistency.
```

2022-08-13 21:28 UTC, jessegmeyerlab commented on content/12.raw-data-analysis.md
> +Measurments of digested purified proteins are great for identifying retention time shifts and mass accuracy problems.
```suggestion

Another strategy is to analyze digested purified proteins, which easily enable discovery of retention time shifts and mass accuracy problems. 
```

2022-08-13 21:28 UTC, jessegmeyerlab commented on content/12.raw-data-analysis.md
> +Carry-over between different measurments can be identified from blank measurements which are subsequently analyzed with your search software of choice.
```suggestion

Carry-over between different measurments can be identified from blank measurements which are subsequently analyzed with your search software of choice.
```

2022-08-13 21:28 UTC, jessegmeyerlab commented on content/12.raw-data-analysis.md
> +Another factor to take into consideration is the stability of your electrospray.
```suggestion

Another factor to take into consideration is the stability of your electrospray.
```

2022-08-13 21:28 UTC, jessegmeyerlab commented on content/12.raw-data-analysis.md
> +Electrospray stability tends to worsen over time with column wear-out, as well as when measuring samples with residual contaminants, such as salts or detergents.
```suggestion
Electrospray stability tends to worsen over time as columns wear, as well as when measuring samples with residual contaminants, such as salts or detergents. 
```

2022-08-15 07:50 UTC, dschust-r commented
Thank you for reviewing and suggesting changes! 
The suggestions all looked sensible to me, I committed them to the branch.

2022-08-15 12:47 UTC, merged