New section and small edits
jessegmeyerlab/proteomics-tutorial pull request #51
Opened 2022-08-17 15:02 UTC by dschust-r

I've added the new proposed section (Biochem basics) and started to write an introduction to proteins and some (non-MS) analysis techniques. I was not sure how detailed that section should be so I kept it a bit more concise.
Also edited some small things in the introduction file (numbering, new section) and in some minor things in the QC software table.
I renumbered the other sections.

Please provide a description of your changes:

Please check the following about your suggested changed:
- [x] The new text has one sentence per line
- [x] preprints that are cited are listed as an issue for discussion and peer review

2022-08-20 18:16 UTC, jessegmeyerlab commented
Thanks Dina, I should be able to review this tomorrow - I'm waiting to merge Norbert's changes since this PR updates all the section numbers

2022-09-03 19:09 UTC, jessegmeyerlab requested changes
Yet another awesome contribution Dina! This will really help those who are coming in without any biochem background. Requesting a few minor changes.

2022-09-03 19:09 UTC, jessegmeyerlab commented on content/03.biochemistry-basics.md
> +The human genome encodes more than 20,000 different proteins of varying abundance.
```suggestion
The human genome encodes more than 20,000 different proteins.
Each protein is present at a different abundances.
```

2022-09-03 19:09 UTC, jessegmeyerlab commented on content/03.biochemistry-basics.md
> +Proteins can be post-translationally modified through enzymatic and non-enzymatic reactions _in vivo_ and _in vitro_.
```suggestion
Proteins can be post-translationally modified through enzymatic and non-enzymatic reactions _in vivo_ and _in vitro_ [@DOI:10.1093/database/baab012]. 
```

2022-09-03 19:09 UTC, jessegmeyerlab commented on content/03.biochemistry-basics.md
> +Deregulation of PTMs is linked to cellular stress and diseases.[@DOI:10.1038/s41570-020-00223-8]
```suggestion
Deregulation of PTMs is linked to cellular stress and diseases[@DOI:10.1038/s41570-020-00223-8].
```

2022-09-03 19:09 UTC, jessegmeyerlab commented on content/03.biochemistry-basics.md
> +Almost all proteins (except for intrinsically disordered proteins) fold into 3D structures either by themselves or assisted through chaperones[@DOI:10.1007/s12013-021-00970-5].
```suggestion
Almost all proteins (except for intrinsically disordered proteins[@DOI:10.1146/annurev-biochem-072711-164947]) fold into 3D structures either by themselves or assisted through chaperones[@DOI:10.1007/s12013-021-00970-5]. 
```

2022-09-05 07:02 UTC, dschust-r commented
Hi Jesse, 

The suggested changes look good to me, I committed them. It seems like there are some merge conflicts (probably because I worked on files that were changed after I had posted my pull-request). Let me know if I should do anything or if you can resolve those conflicts.

2022-09-09 02:13 UTC, jessegmeyerlab commented
> 

Is it possible to remove the renaming of section 04 from this and then I will do it manually after ?

2022-09-09 07:08 UTC, closed without merging