Update 10.mass-spectrometers.md
jessegmeyerlab/proteomics-tutorial pull request #79
Opened 2023-09-05 19:16 UTC by jymbcrc

Please provide a description of your changes:

Please check the following about your suggested changed:
- [ ] The new text has one sentence per line
- [ ] preprints that are cited are listed as an issue for discussion and peer review

2023-09-05 21:59 UTC, jymbcrc reviewed
more stuff are waiting for uploading

2023-09-05 22:40 UTC, jymbcrc reviewed
working on uploading figures, tables, and adding reference

2023-09-27 18:37 UTC, jessegmeyerlab requested changes

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Mass spectrometry serves as a sophisticated instrument for determining the masses of compounds and elements, is a science of ions.
```suggestion
Mass spectrometry is a science of ions; it serves as a sophisticated instrument for determining the masses of compounds and elements. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +It can be likened to an ultra-precise scale that can differentiate mass variations down to a single proton or even lower.
```suggestion
It can be likened to an ultra-precise weigh scale that can differentiate mass variations down to a single electron, or even lower. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Since J.J. Thomson's initial exploration in 1912, the field of mass spectrometry has undergone numerous improvements, spanning from isotope assessment to the interpretation of biomacromolecules[@DOI:
```suggestion
Since J.J. Thomson's initial exploration in 1912, the field of mass spectrometry has undergone numerous improvements, spanning from isotope assessment to the interpretation of biomacromolecules [@DOI:10.1021/ac8013065], all thanks to the combined efforts of diverse fields like chemistry, physics, electronic engineering, and computer science. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Nowadays, with the rapid improvement of sensitivity, mass resolution, tandem mass spectrometry methods and dissociation methods, mass spectrometers have evolved as a core tool for proteomics and meta
```suggestion
Nowadays, with the rapid improvement of sensitivity, mass resolution, tandem mass spectrometry methods and dissociation methods, mass spectrometers have evolved as a core tool for proteomics (and metabolomic) analysis.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Additionally, it is precisely the widespread application of mass spectrometry in omics analysis that has given rise to more instrument manufacturers and a greater diversity of mass spectrometer types
```suggestion
It is precisely the widespread application of mass spectrometry in proteomics analysis that has given rise to more instrument manufacturers and a greater diversity of mass spectrometer types. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +This also brings a happy annoyance to many beginners or researchers in other fields who have no background in mass spectrometry: which manufacturer and which type of mass spectrometry should I choose
```suggestion
This also brings a happy annoyance to many beginners or researchers in other fields who have no background in mass spectrometry: which manufacturer and which type of mass spectrometry should I choose to analyze my samples? 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +### Structure and principles
```suggestion

### Mass Spectrometer Structure and Basic Principles   
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +The fundamental principle of mass spectrometry revolves around specific physical processes and mathematical formulas.
```suggestion
The fundamental principle of mass spectrometry revolves around specific physical processes that can be described by various mathematical formulas. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +The process of mass spectrometry (MS) is to generate gas phase ions from compounds in samples by any suitable method, to separate these ions by their mass-to-charge ratio (m/z), and then detect them
```suggestion

The process of mass spectrometry (MS) is to generate gas phase ions from compounds in samples by any suitable method, to separate these ions by their mass-to-charge ratio (m/z), and then detect them by their respective m/z and abundance. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +The successful implementation and demonstration of this process requires participation of five fundamental systems (images/ms_f101.svg) (Figure 10.1):
```suggestion
The successful implementation and demonstration of this process requires participation of five fundamental systems (Figure X):
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +2)	The mass analyzer, where gas phase ions are separated according to their mass-to-charge ratio (m/z) based on physic principles.
```suggestion
2)	The mass analyzer, where gas phase ions are separated according to their mass-to-charge ratio (m/z) based on physics principles.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +There are several types of mass analyzers applied in mass spectrometry, such as time-of-flight (TOF), quadrupole, ion trap, orbitrap, Fourier transform-ion cyclotron resonance (FT-ICR), and magnetic
```suggestion
There are several types of mass analyzers applied in mass spectrometry, such as time-of-flight (TOF), quadrupole, ion trap, orbitrap, Fourier transform-ion cyclotron resonance (FT-ICR), and magnetic sector analyzers [@DOI:10.3389/fchem.2021.813359; @DOI:10.1146/annurev-anchem-071114-040325], each with unique advantages and applications (Table 10.1).
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +4)	The vacuum system, which is designed to maintain a vacuum environment for ions’ movement inside the instrument, are consist of different type of pumps including rough vacuum pumps (rotary vane pum
```suggestion
4)	The vacuum system, which is designed to maintain a vacuum environment for ions’ movement inside the instrument, consists of different type of pumps including rough vacuum pumps (rotary vane pumps, scroll pumps) and high vacuum pumps (turbo molecular pumps, diffusion pumps).
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +For proteomic analysis, tandem mass spectrometry, which involves combining two or three different mass analyzers, is typically used to achieve precursor selection, structural analysis, improved sensi
```suggestion
For proteomic analysis, tandem mass spectrometry, which involves combining two or more mass analyzers, is typically used to achieve precursor selection, structural analysis, improved sensitivity, and better mass resolution [@DOI:10.1016/j.jasms.2007.11.013].
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +The reason for maintaining a high vacuum is to reduce the collision between ions and gas molecules during their travel, which can affect their trajectory and patterns.
```suggestion
The reason for maintaining a high vacuum is to reduce the collision between ions and gas molecules during their travel, which can affect their trajectory.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +FT-ICR and Orbitrap usually require higher vacuum in the 10-9 to 10-11 Torr level, while TOF requires medium vacuum in the 10-7  to 10-8 Torr range, and Quadrupole and Ion trap require a relative low
```suggestion
FT-ICR and Orbitrap instruments usually require higher vacuum in the 10-9 to 10-11 Torr level, while TOFs require medium vacuum in the 10-7  to 10-8 Torr range, and Quadrupole and Ion trap require a relative lower vacuum in the 10-5  to 10-6 Torr range. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +| Type | Acronym | Principle | Characters |
```suggestion
| Type | Acronym | Principle | Characteristics |
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +| Linear quadrupole | Q | Continuous ion beam in linear radio frequency quadrupole field; separation due to instability of ion trajectories |High transmission efficiency. simple design, good sensitiv
```suggestion
| Linear quadrupole | Q | Continuous ion beam in linear radio frequency quadrupole field; separation due to instability of ion trajectories |High transmission efficiency, simple design, good sensitivity, and tunable mass range; relatively low mass resolution ranges from several hundreds to a thousand; often used in tandem mass spectrometry (MS/MS) experiments |
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +| Fourier transform-ion cyclotron resonance | FT-ICR | Traps ions in a strong magnetic field by Lorentz force; separation by cyclotron frequency, image current detection and Fourier transformation of
```suggestion
| Fourier transform-ion cyclotron resonance | FT-ICR | Traps ions in a strong magnetic field by Lorentz force; separation by cyclotron frequency, image current detection and Fourier transformation of transient signal |Ultimate high mass resolution (up to 1,000,000), making it ideal for elemental and isotopic analysis. Large size, low speed, and expensive in terms of both initial purchase cost and ongoing operation and maintenance costs. |
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +| Type | Principle | Characters |
```suggestion
| Type | Principle | Characteristics |
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +| Electron Multiplier | Amplifies signals by utilizing a sequence of dynodes that emit secondary electrons when struck by an incident electron, creating a cascading effect. This results in an amplifi
```suggestion
| Electron Multiplier | Amplifies signals by utilizing a sequence of dynodes that emit secondary electrons when struck by an incident electron, creating a cascading effect. This results in an amplified output current at the final anode, proportional to the intensity of the initial signal. | Very good signal amplification to even one electron (may cause more noise dependent on gain), high sensitivity, need high vacuum and high voltage, expensive. Limited dynamic range, finite lifespan and need to be replaced periodically |
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +| Microchannel Plate | Similar to electron multiplier, a two-dimensional matrix or "plate" of many tiny, parallel, hollow channels made from a type of glass that can generate secondary electron emiss
```suggestion
| Microchannel Plate | Similar to electron multiplier, a two-dimensional matrix or "plate" of many tiny, parallel, hollow channels made from a type of glass that can generate secondary electron emissions upon incident particles striking the channel walls.  These secondary emissions create an electron avalanche down the channels and amplifies the original signal. | Signal Amplification (Not as good as electron multiplier, but lower noise), Spatial Resolution ability, shorter life expectancy due to channel aging and depletion of the secondary emission material, smaller and cheaper than electron multiplier |
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +
```suggestion
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +### 1. Triple quadrupole
```suggestion
### 1. Triple quadrupole (QQQ).
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Triple quadrupole mass spectrometer (often abbreviated as QqQ, TQ, or TQMS), as suggested by the name, is a type of tandem mass spectrometer that three quadrupole mass analyzers are combined in serie
```suggestion
Triple quadrupole mass spectrometer (often abbreviated as QqQ, QQQ, TQ, or TQMS), as suggested by the name, is a type of tandem mass spectrometer where three quadrupole mass analyzers are combined in series (Figure 10.2). 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Each quadrupole is essentially a set of four parallel metal rods to which radio frequency (RF) and direct current (DC) voltages are applied to each opposing pair of rods. The QqQ operate in a synchro
```suggestion
Each quadrupole is essentially a set of four parallel metal rods to which radio frequency (RF) and direct current (DC) voltages are applied to each opposing pair of rods. 
The QqQ operate in a synchronized manner to isolate ions of interest (according to the Mathieu function), induce fragmentation, and then detect the resulting fragment ions. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +This is achieved by adjusting the voltage applied to the pair rods within the quadrupole, allowing ions with a particular m/z value to pass through while deflecting others. Second quadrupole (Q2), al
```suggestion
This is achieved by adjusting the voltage applied to the pair rods within the quadrupole, allowing ions with a particular m/z value to pass through while deflecting others. 
The second quadrupole (Q2), also known as the collision cell, is where selected ions from Q1 are fragmented into product ions. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +This fragmentation happens due to the collisions between inert gas molecules (nitrogen, argon, or helium) and ions, which causes the ions to break up (fragment) into smaller pieces (fragment ions).
```suggestion
This fragmentation happens due to the collisions between inert gas molecules (nitrogen, argon, or helium) and ions, which causes the ions to break up (fragment) into smaller pieces (fragment ions). 
For more detail about peptide fragmentation, see the Tandem Mass Spectrometry section.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +This process is known as collision-induced dissociation (CID)[@DOI:10.1016/S0076-6879(05)02005-7; @DOI:10.1021/ac00106a008].
```suggestion
This process is known as collision-induced dissociation (CID) [@DOI:10.1016/S0076-6879(05)02005-7; @DOI:10.1021/ac00106a008]. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +The chosen ions are then directed to the detector, where their abundance is measured (images/ms_f102.svg)(Figure 10.2).
```suggestion
The chosen ions are then directed to the detector, where their abundance is measured (Figure 10.2). 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +This process, involving precursor ions selection, precursor ions fragmentation, and product ions detection, is a general operating principle in tandem mass spectrometry and determines what kind of sc
```suggestion
This process, involving precursor ion selection, precursor ion fragmentation, and product ion detection, is a general operating principle in tandem mass spectrometry and determines what kind of scan mode you can utilize.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +A key characteristic and advantage of QqQ is the flexibility of choosing various scan modes[@DOI:10.1021/ac00219a003; @DOI:10.1002/jms.703;10.1021/ac00106a008], including:
```suggestion
A key characteristic and advantage of QqQ is the flexibility of choosing various scan modes[@DOI:10.1021/ac00219a003; @DOI:10.1002/jms.703;10.1021/ac00106a008], such as the following.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +(1) Product Ion Scan: Q1 is set to filter a specific precursor ion, which is then fragmented in Q2. Q3 scans the full range of product ion masses. This mode is usually used to identify the structure
```suggestion
1. Product Ion Scan: Q1 is set to filter a specific precursor ion, which is then fragmented in Q2. 
Q3 scans the full range of product ion masses. 
This mode is usually used to identify the structure of a particular compound. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +(2) Precursor Ion Scan: Q3 is set to filter a specific product ion. Q1 scans the full range of precursor ions that, when fragmented in Q2, yield the selected product ion.
```suggestion
2. Precursor Ion Scan: Q3 is set to filter a specific product ion. 
Q1 scans the full range of precursor ions, that when fragmented in Q2, yield the selected product ion. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Figure 10.2 Schematic diagram of typical QqQ system.
```suggestion
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +![**Figure 10.2 Schematic diagram of typical QqQ system.**](images/MS_f102.svg){#fig:figure10.2 tag="2" width="9%"}.
```suggestion
![**Schematic diagram of typical QqQ system**](images/MS_f102.svg){#fig:figure10.2 tag="2" width="9%"}.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +An alternative way to expand drift length and achieve higher resolution is to apply reflector (often called a reflectron) for TOF.
```suggestion
An alternative way to expand drift length and achieve higher resolution is to apply reflector (often called a reflectron) for TOF. 
```
```suggestion
An alternative way to expand drift length and achieve higher resolution is to apply reflector (often called a reflectron). 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +1) Under ideal circumstances within a TOF mass spectrometer, ions sharing the same m/z would reach the detector concurrently post-acceleration, thus generating a sharp peak on the mass spectrum.
```suggestion
Under ideal circumstances within a TOF mass spectrometer, ions sharing the same m/z would reach the detector concurrently post-acceleration, thus generating a sharp peak on the mass spectrum.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +The principles and advantages of using a reflector can be summarized as follows:
```suggestion
The principles and advantages of using a reflector can be summarized as follows.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +As such, reflecting TOF forms the basis of most commercial instruments currently in use.
```suggestion
This reflection comes at the cost of some ion loss, and therefore some sensitivity loss. 
As such, reflecting TOFs are the basis of most commercial instruments currently in use.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +1) Quadrupole mass analyzer (Q): This part of the instrument is basically the same to the Q1 in QqQ, which select specific m/z values to pass through by applying a combination of DC and RF voltages a
```suggestion
1. Quadrupole mass analyzer (Q): This part of the instrument is basically the same to the Q1 in QqQ, which select specific m/z values to pass through by applying a combination of DC and RF voltages across the rods.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +2) Collision cell: Here, selected ions undergo collision-induced dissociation (CID) by interacting with a neutral gas, leading to their fragmentation into smaller constituents.
```suggestion
2. Collision cell: Here, selected ions undergo collision-induced dissociation (CID) by interacting with a neutral gas, leading to their fragmentation into smaller constituents.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +3) Time-of-Flight (TOF) mass analyzer: Upon exiting the collision cell, the fragmented ions are reaccelerated into the ion modulator region of the time-of-flight analyzer.
```suggestion
3. Time-of-Flight (TOF) mass analyzer: Upon exiting the collision cell, the fragmented ions are reaccelerated into the ion modulator region of the time-of-flight analyzer.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +TOF generally offers mass resolutions surpassing 50,000, rendering it a reliable instrument for identifying unknown compounds.
```suggestion
TOFs generally offer mass resolutions surpassing 50,000, rendering it a reliable instrument for identifying unknown compounds.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Moreover, the rapid travel time of ions in the vacuum tube (at the nanosecond level) confers Q-TOF with distinctive benefits in short gradient and high-throughput analyses [@DOI:10.1101/657908;@DOI:1
```suggestion
Moreover, the rapid travel time of ions in the vacuum tube (at the nanosecond level) confers the Q-TOF with distinctive benefits in short gradient and high-throughput analyses [@DOI:10.1101/657908;@DOI:10.1021/acs.jproteome.1c00446;@DOI:10.1074/mcp.M400161-MCP200].
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Sciex: “TripleTOF® 6600+”, “TripleTOF® 5600+” System and “X500R QTOF” System, etc.
```suggestion
Sciex: “TripleTOF® 6600+”, “TripleTOF® 5600+” System and “X500R QTOF” System.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Bruker Corporation: “Impact II”, “timsTOF” series, “microTOF-Q III”, “ultrafleXtreme-MALDI-TOF/TOF” and “maXis II”, etc.
```suggestion
Bruker Corporation: “Impact II”, “timsTOF” series, “microTOF-Q III”, “ultrafleXtreme-MALDI-TOF/TOF” and “maXis II”.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Agilent Technologies: “Agilent 6530 Accurate-Mass Q-TOF”, “Agilent 6545 Accurate-Mass Q-TOF”, and “Agilent 6550 iFunnel Q-TOF”, etc.
```suggestion
Agilent Technologies: “Agilent 6530 Accurate-Mass Q-TOF”, “Agilent 6545 Accurate-Mass Q-TOF”, and “Agilent 6550 iFunnel Q-TOF”.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Waters Corporation: “SYNAPT G2-Si HDMS”, “Xevo G2-XS QToF ” and “SYNAPT XS”, etc.
```suggestion
Waters Corporation: “SYNAPT G2-Si HDMS”, “Xevo G2-XS QToF ” and “SYNAPT XS”.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +![**Figure 10.3 Schematic diagram of a typical quadrupole time-of-flight mass spectrometer.**](images/MS_f103.svg){#fig:figure10.3 tag="3" width="80%"}.
```suggestion
![**Schematic diagram of a typical quadrupole time-of-flight mass spectrometer.**](images/MS_f103.svg){#fig:figure10.3 tag="3" width="80%"}.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Figure 10.3 Schematic diagram of a typical quadrupole time-of-flight mass spectrometer.
```suggestion
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +In the late 20th century, Russian scientist Alexander Makarov invented the Orbitrap[@DOI:10.1021/ac991131p], which is a novel mass analyzer that operates based on the principle of electrodynamic ion
```suggestion
In the late 20th century, Russian scientist Alexander Makarov invented the Orbitrap [@DOI:10.1021/ac991131p], which is a novel mass analyzer that operates based on the principle of electrodynamic ion trapping and Fourier Transform. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +The ions are trapped in an orbit around the spindle electrode due to the electrostatic attraction. Once inside, the ions begin oscillating along the central axis of the device, or "orbiting", due to
```suggestion
The ions are trapped in an orbit around the spindle electrode due to the electrostatic attraction. 
Once inside, the ions begin oscillating along the central axis of the device, or "orbiting", due to the electric field formed by the inner and outer electrodes. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +The oscillation frequency of an ion is inversely proportional to the square root of its mass-to-charge ratio. The frequency at which each ion oscillates induces an image current on the detector, whic
```suggestion
The oscillation frequency of an ion is inversely proportional to the square root of its mass-to-charge ratio. 
The frequency at which each ion oscillates induces an image current on the detector, which can be measured and transformed into a mass spectrum using Fourier transform. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Just like Q-TOF, Orbitrap was also usually used as a part of tandem mass spectrometry.
```suggestion
Just like the Q-TOF, the Orbitrap is also usually used for tandem mass spectrometry. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Compared to TOF, one disadvantage of the Orbitrap is its longer cycle time (AGC pre-scan, ion injection, ion isolation, ion activation and mass analysis, usually >100ms), which is a negative factor f
```suggestion

Compared to a TOF, one disadvantage of the Orbitrap is its longer cycle time (AGC pre-scan, ion injection, ion isolation, ion activation and mass analysis, usually >100ms), which is a negative factor for the currently favored short gradient, high-throughput analysis. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +At present, Orbitrap still dominates important applications in almost all aspects of proteomics including biomarker discovery[@DOI:10.1186/s12014-015-9102-9], post-translational modification (PTM) an
```suggestion
At present, the Orbitrap still dominates important applications in almost all aspects of proteomics including biomarker discovery[@DOI:10.1186/s12014-015-9102-9], post-translational modification (PTM) analysis[@DOI:10.1093/database/baab012; @DOI:10.1038/nmeth.4334], quantitative proteomics (LFQ, TMT, iTRAQ)[@DOI:10.1021/acs.analchem.2c02249; @DOI:10.1021/jasms.3c00072; @DOI:10.1038/s41592-020-00999-z], protein-protein interaction studies[@DOI:10.1016/j.tibtech.2016.02.014] and structural proteomics[@DOI:10.1038/s41467-021-27588-8; @DOI:10.1021/acs.analchem.1c03274]. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +It can perform both top-down and bottom-up analyses owing to its broad mass range, and suitable for both Data-Dependent Acquisition (DDA) and Data-Independent Acquisition (DIA) methods.
```suggestion
It can perform both top-down and bottom-up analyses owing to its broad mass range, and is suitable for both Data-Dependent Acquisition (DDA) and Data-Independent Acquisition (DIA) methods. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Right now. the Orbitrap is still under patent protection and only one company, ThermoFisher, is allowed to manufacture related products.
```suggestion
Right now, the Orbitrap is still under patent protection and only one company, ThermoFisher, is allowed to manufacture related products. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Classic models from ThermoFisher include Orbitrap Ascend Tribrid, Orbitrap Eclipse™ Tribrid™, Orbitrap Fusion™ Lumos™, Orbitrap Exploris series (120, 240, 480) and Q Exactive™ series, etc.
```suggestion
Classic models from ThermoFisher include Orbitrap Ascend Tribrid, Orbitrap Eclipse™ Tribrid™, Orbitrap Fusion™ Lumos™, Orbitrap Exploris series (120, 240, 480) and Q Exactive™ series. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +![**Figure 10.4 Schematic diagram of orbitrap (A) and typical Q-Orbitrap system (B).**](images/MS_f104.svg){#fig:figure10.3 tag="3" width="100%"}.
```suggestion
![**Schematic diagram of orbitrap (A) and typical Q-Orbitrap system (B).**](images/MS_f104.svg){#fig:figure10.3 tag="3" width="100%"}.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Figure 10.4 Schematic diagram of orbitrap (A) and typical Q-Orbitrap system (B).
```suggestion
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +The ions absorb radio frequency energy, which increases the radius of their circular path, and consequently, getting closer to the detector plates and generating a receivable current signal.
```suggestion
The ions absorb radio frequency energy, which increases the radius of their circular path, and consequently, the excited ions move closer to the detector plates and generate a current. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Similar to Orbitrap, this time-domain signal is then transformed into a frequency-domain signal using Fourier transform, hence the name Fourier Transform ICR.
```suggestion
Similar to Orbitrap, this time-domain signal is then transformed into a frequency-domain signal using Fourier transform, hence the name Fourier Transform ion cyclotron resonance (ICR). 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Another significant benefit of FT-ICR is its broad mass range, making it possible to identify macromolecules like proteins and workable for top-down proteomics[@DOI:10.1002/mas.20015;@DOI:10.1021/acs
```suggestion
Another significant benefit of FT-ICR is its broad mass range, making it possible to identify macromolecules like proteins for top-down proteomics[@DOI:10.1002/mas.20015;@DOI:10.1021/acs.analchem.7b04747; ]. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Despite its advantages, FT-ICR mass spectrometry is not without challenges.
```suggestion

Despite its advantages, FT-ICR mass spectrometry is not without challenges. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +A schematic representation of a Q-FT-ICR system was further depicted in Figure 10.5 B.
```suggestion
A schematic representation of a Q-FT-ICR system is shown in Figure 10.5 B. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +![**Figure 10.5 Schematic diagram of ICR cell (A) and typical Q-FT-ICR system (B).**](images/MS_f105.svg){#fig:figure10.3 tag="5" width="100%"}.
```suggestion
![**Schematic diagram of ICR cell (A) and typical Q-FT-ICR system (B).**](images/MS_f105.svg){#fig:figure10.3 tag="5" width="100%"}.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Figure 10.5 Schematic diagram of ICR cell (A) and typical Q-FT-ICR system (B).
```suggestion
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +
```suggestion
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Mass spectrometry alone can only provide two-dimension data including mass-to-charge ratio and their intensity.
```suggestion
Mass spectrometry alone can only provide two-dimensional data including mass-to-charge ratio and their intensity. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Although the Mason-Schamp equation isn't universally embraced, it is currently the primary formula the community uses to compute CCS. In basic terms, the CCS serves as a standard metric for the size
```suggestion
Although the Mason-Schamp equation isn't universally embraced, it is currently the primary formula the community uses to compute CCS. 
In basic terms, the CCS serves as a standard metric for the size in the gas phase, generally expressed in units of square Angströms (Å2). 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Hence, direct comparison of CCS value between different platforms should be careful and calibration might be necessary.
```suggestion
Hence, direct comparison of CCS value between different platforms often requires calibration.  
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Generally, ion mobility techniques can be categorized into three separation concepts: (1) temporally dispersive, (2) spatially dispersive, and (3) ion confinement (trapping) and selective release (Fi
```suggestion

Generally, ion mobility techniques can be categorized into three separation concepts: (1) temporally dispersive, (2) spatially dispersive, and (3) ion confinement (trapping) and selective release (Figure 10.6 A)[@DOI:10.1021/ac8013669].
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Typical ion mobilities of this technique including High Field Asymmetric Waveform Ion Mobility Spectrometry (FAIMS), uniform-field differential mobility analyzers (DMA), and the newly introduced scan
```suggestion
Types of spatially dispersive ion mobility include High Field Asymmetric Waveform Ion Mobility Spectrometry (FAIMS), uniform-field differential mobility analyzers (DMA), and the newly introduced scanned frequency ion mobility filter called transverse modulation ion mobility spectrometry (TMIMS). 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +| Separation concept | Ion mobility techniques | Ion movement direction | Electric field direction | Drift Gas direction | Characters |
```suggestion
| Separation concept | Ion mobility techniques | Ion movement direction | Electric field direction | Drift Gas direction | Characteristics |
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +Figure 10.6 Conceptional diagram of three types of ion mobility strategies (A) and schematic diagrams of three emerging IM techniques: (B) drift tube ion mobility spectrometry. (C) high field asymmet
```suggestion
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +![**Figure 10.6 IM-MS.**](images/MS_f106.svg){#fig:figure10.6 tag="6" width="100%"}.
```suggestion
![**Figure 10.6 IM-MS.**
Conceptional diagram of three types of ion mobility strategies (A) and schematic diagrams of three emerging IM techniques: (B) drift tube ion mobility spectrometry. 
(C) high field asymmetric waveform ion mobility spectrometry (FAIMS). 
(D) trapped ion mobility spectrometry (TIMS). 
](images/MS_f106.svg){#fig:figure10.6 tag="6" width="100%"}.
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +However, DTIMS also suffers from disadvantages including: 1) separation time is too long for all ions passing through the drift tube, relative to the accumulation time, decreases the duty cycle.
```suggestion
However, DTIMS also suffers from disadvantages including: 1) separation time is too long for all ions passing through the drift tube, relative to the accumulation time, which decreases the duty cycle. 
```

2023-09-27 18:37 UTC, jessegmeyerlab commented on content/10.mass-spectrometers.md
> +The drawback of FAIMS is it cannot produce any CCS value and its low resolving power. Commercial FAIMS products from vendors including Thermo Fisher and WATERS are available now.
```suggestion
The drawback of FAIMS is it cannot produce any CCS value and its low resolving power. 
Commercial FAIMS products from vendors including Thermo Fisher and WATERS are available now.
```

2023-09-27 18:43 UTC, merged